name: Close All Pull Requests

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: crondaemon/close-pr@v1
      with:
        comment: "We do not accept PRs."
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
